# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory containing .bb and .bbappend files, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb \
            ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "myhome-rpi"
BBFILE_PATTERN_myhome-rpi := "^${LAYERDIR}/"
BBFILE_PRIORITY_myhome-rpi = "9"

LAYERSERIES_COMPAT_myhome-rpi = "wrynose"
LAYERDEPENDS_myhome-rpi = "raspberrypi"

# Additional license directories.
#LICENSE_PATH += "${LAYERDIR}/files/custom-licenses"
